dist: trusty
sudo: required
services:
- docker
language: go
go:
- "1.10.x"

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor

script:
- find . -type f -name "*.go" | xargs sed 's|github.com/terraform-providers/terraform-provider-azurerm|github.com/criteo-forks/terraform-provider-azurerm|' -i
- export VERSION=$(echo $TRAVIS_TAG | sed 's/^v//')
- make fmt
- gofmt -s -w main.go
- make -j 3 multiarch


before_deploy:
  - echo "Deploying $VERSION to GitHub releases"
  - for d  in $(find ./pkg/bin -maxdepth 1 -mindepth 1 -type d | cut -d '/' -f4); do zip -j terraform-provider-azurerm_${VERSION}_${d}.zip ./pkg/bin/${d}/terraform-provider-azurerm* ; done

deploy:
  provider: releases
  file_glob: true
  file: terraform-provider-azurerm_*.zip
  skip_cleanup: true
  on:
    repo: criteo-forks/terraform-provider-azurerm
    tags: true

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
