dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.10.x
install:
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
script:
- find . -type f -name "*.go" | xargs sed 's|github.com/terraform-providers/terraform-provider-azurerm|github.com/criteo-forks/terraform-provider-azurerm|'
  -i
- export VERSION=$(echo $TRAVIS_TAG | sed 's/^v//')
- make fmt
- gofmt -s -w main.go
- make -j 3 multiarch
before_deploy:
- echo "Deploying $VERSION to GitHub releases"
- for d  in $(find ./pkg/bin -maxdepth 1 -mindepth 1 -type d | cut -d '/' -f4); do
  zip -j terraform-provider-azurerm_${VERSION}_${d}.zip ./pkg/bin/${d}/terraform-provider-azurerm*
  ; done
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key:
    secure: SNA25F92JVKSuCtNOl1OwA7Jv6S40Azg8dbqlZz2F6hPgpORHrOotQy1hZNhoAylinIpkFXXIUHhY9ekI5YBWkty3nNpeEEVnrdOAW5bgbxarcFXIa5EAjqLRDYNWAJCiwoYp77Vfvfdbct1r2UYvh2GXRZF08/bgnJos7RujTLLfNX7uk+Thr/IMISSoFa+Kr+IDU5r0Dz0AgZIkTVwb5yFVak4fpR1a+YWKGnqXH8tnknl/qqjWSq3/Wtsb+GV1/lD/RnXVP+RW2FTY8d4sbBJBczb8JUiI0Af3OJwMF0QH5BI+Dp5KxTNr0fvaBQ34+dpSckJl/b+odePmfJ9zC0hHlf5fBlS8FXCOVg9+Ijp7YzKs3IvGdXeY9ZLSf+WBZiQGoUD94QJddEdN+LPnKqJT97gNEHxZ8UKmogive+W6TbF/4wd8aDWt+0Qyog2n/TjE+h0deByZ9mtAjYVA25SDG5sSI3Ea5C0gWH5sPiQXgMXZnbcwjIVg8/wvpEC+JiMvELV1I2KqUpGH0eP16sabdrYKqu6in5W8isjNknMtd9mvz8qtLtC9iisE7t4FykNHdTKC4R8PzYxGCsDSrmRf4gDHfZ6QDyuJ9WqFRoX7k21kUvjqg/4Xpa/VpVXgip4zOnQYHdqTxgSZOhTNSzT48W++3g4By/dypcZYSA=
  file: "*.zip"
  skip_cleanup: true
  file_glob: true
  on:
    repo: criteo-forks/terraform-provider-azurerm
    tags: true
