dist: trusty
sudo: required
services:
- docker
language: go
go:
- "1.11.x"

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

script:
- find . -type f -name "*.go" | xargs sed 's|github.com/terraform-providers/terraform-provider-azurerm|github.com/criteo-forks/terraform-provider-azurerm|'
  -i
- export VERSION=$(echo $TRAVIS_TAG | sed 's/^v//')
- make fmt
- gofmt -s -w main.go
- make -j 3 multiarch

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

before_deploy:
- echo "Deploying $VERSION to GitHub releases"
- for d  in $(find ./pkg/bin -maxdepth 1 -mindepth 1 -type d | cut -d '/' -f4); do
  tar czf terraform-provider-azurerm-${VERSION}.${d}.tar.gz -C ./pkg/bin/${d} .
  ; done
deploy:
  provider: releases
  api_key:
    secure: WF7V765NcHVPLS99QxUiZJy0b3tRYIWcvnhHZULRIuPPQgTccFoVa3FlEDsK42Vxh2mCapmwYLt2U/rtAt5ZLVXq82GTb9JPdgQ4UZ4/3D23pwQuh6VVt5VFjCR9eYq3yoDurW47TxYfszkTO5Fhlg7voP8YMP8uxXWRPjBSNn3y/KRrSOPFzFMRdy0Vwvx0s06Yw3sIMdF3QVx4p1mKp9DPPxxcH6MAYO0X0LSu4hqyya4omvBExh5AhUfMoCiWY2eGIIK4J/bbcS+/XVwiqurTdCE+uMQItHw7qR4ReSORJvv2HUUDEh1ad9OaHhMU9xXcV2hhGlYXgtq5lWjrEfaYPn89YHZZb9Wev3GHSdKvXAaU1Ld1KjqtGp4Wfvx+C/PB4OSeY4LUhR8eIKFgBRSS24PENgnCS7S87WJGAwhSItfsbJc1ZFhSCfnYP5da7eHBif9kb8rPPCLCPlFejBLmyMtKHhrs1qb1ocyaF8E93A3v2Bs8f/p+DngI/HfDDlNNivTbt1MiC/Ttd+R2BDwqnPpnF0oJ/+rNrz0f3qukeIgWxGpcWIokPV1hyiHPmhlre8gVHwtpgWdTXO1qw9FJjfg3RgKH6AoptqLGmYBg3NKnbWBsipgOZnccspqhftC4XKBHbgzfGoi2Ni3ojuLGs5G7h0CftC6MsMbt558=
  file_glob: true
  skip_cleanup: true
  file: terraform-provider-azurerm-${VERSION}.*.tar.gz
  on:
    repo: criteo-forks/terraform-provider-azurerm
    tags: true
