dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - 1.10.x
install:
  - bash scripts/gogetcookie.sh
  - make tools
script:
  - find . -type f -name "*.go" | xargs sed 's|github.com/terraform-providers/terraform-provider-azurerm|github.com/criteo-forks/terraform-provider-azurerm|'
    -i
  - export VERSION=$(echo $TRAVIS_TAG | sed 's/^v//')
  - make fmt
  - gofmt -s -w main.go
  - make -j 3 multiarch
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
before_deploy:
  - echo "Deploying $VERSION to GitHub releases"
  - for d  in $(find ./pkg/bin -maxdepth 1 -mindepth 1 -type d | cut -d '/' -f4); do
    tar czf terraform-provider-azurerm-${VERSION}.${d}.tar.gz -C ./pkg/bin/${d} . ;
    done
deploy:
  provider: releases
  api_key:
    secure: H4AQUXxJSI5Pl1bP1HF9OSFc+YDqIKaw8uz48KkZ49xKF8vbnDPoUkA/igO4EmJi9Hc0FBPkEKaHl9cvYwNVrcENXaKPFEn/BEJu/33sb1gH6AJj9eIp1mAyHW0IoKBe0exvA+r5SoEWZ1awm05rTymre7vLgNKa0xiGl8SHaQN2OMCSFCdRHOxzzs7Jmdgi5MhsQuAWWbymns/qZ+rBqVkk4s0tHHYLrovBMcbRo3nQf73ZO9oA6kt61nl3am+6lVN4qrQrpIMwBp+TvtPNRUrmxr0W99o9x3oLinFrAEqNSWi9D2BqxK24pvXKGDmnZQ+6KmEUesRA1OL554O7+ppit+ni/t/FTNGwoToR+94cEo+jSSFR3KZEep7Wi8rXZfQv6KZJMkWma3cm+cgzhPc8POF19mqcpFmRMMVSZKapOTJ56HPixk5nnIWj4fzhtKwBEGiraEfr7bJy1wUEgEtAR4FnGbknGJn51se2QWBWnQT600XDFiFjQfjVh43CtXnOhYFQG8GAKkNiwb1HQRFUo1HTxTwC93JYPlGyJI6wONu7s2WsKO4hmmWFX3FPg52+EtoH1D2axd9sPp/I6d9KyQ007GMayKBB97DBUxC8nGCwo/eSOjaLUvijdq2kMkvBUuALFBDuWZ+F5w9fEdIJyLVmnLqCki2wFr+dxk4=
  file_glob: true
  skip_cleanup: true
  file: terraform-provider-azurerm-${VERSION}.*.tar.gz
  on:
    repo: criteo-forks/terraform-provider-azurerm
    tags: true
